export const packages = [
  {
    name: "Amateur",
    services: "5 Services",
    startingPrice: "$750",
    price: "$700.00",
    features: [
      "Professional MLS Photography",
      "Drone Photography (Aerial Stills)",
      "Signature Listing Video",
      "Twilight Photo Add'l/Stills",
      "Floor Plans and Measurements",
    ],
    highlighted: false,
  },
  {
    name: "Core",
    services: "6 Services",
    startingPrice: "$3,000",
    price: "$1,000.00",
    features: [
      "Professional MLS Photography",
      "Drone Photography (Aerial Stills)",
      "Signature Listing Video",
      "Twilight Photo Add'l/Stills",
      "Platinum Reel",
      "Custom Listing Website",
    ],
    highlighted: false,
  },
  {
    name: "Dominance",
    services: "8 Services",
    startingPrice: "$4,500",
    price: "$1,300.00",
    features: [
      "Professional MLS Photography",
      "3D Floor Plans and Measurements",
      "20 High-Res Digital Stills",
      "Twilight Photo Add'l/Stills",
      "Platinum Reel",
      "Tower Video",
      "Custom Listing Website",
      "Social Media (Story Sessions)",
    ],
    highlighted: true,
  },
  {
    name: "Custom",
    services: "5+ Services",
    startingPrice: "Custom",
    price: "CUSTOM",
    features: [
      "Professional MLS Photography",
      "Drone Photography (Aerial Stills)",
      "Custom Listing Website",
      "Brand Authority Sessions",
      "Dedicated Content Strategy",
    ],
    highlighted: false,
  },
];